typography_spectrum: 0.4910394
color:
  saturation: 1
  brandStrength: 0.162602
  lightness: 1
  rhythmicContrast: 1
layout_spectrum: 0
name: BenEaston
navigation:
  - name: People!!!
    id: 11731975-1496-4c0d-9b9c-bf448bf9e92a
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Ben Easton
